# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(auto_created=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
