# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='number',
        ),
    ]
