# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Qualification')),
            ],
        ),
    ]
