# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_result_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='result_id',
        ),
        migrations.AddField(
            model_name='result',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
            preserve_default=False,
        ),
    ]
