# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20160812_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='name',
            new_name='comment',
        ),
    ]
